services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped  # Автоперезапуск при падении
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3

  bot:
    build: .
    container_name: bot
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      MONGODB_URI: "mongodb://root:example@mongo:27017"
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mongo_data: